version: '3.3'
services:
  app:
    build: .
    environment:
      DBHOST: '$DBHOST'
      DBPASS: '$DBPASS'
      DBUSER: '$DBUSER'
      DBNAME: '$DBNAME'
    ports:
      - '8080:8080'
    expose:
      - '8080'